backend:
  name: git-gateway
  branch: master
media_folder: public/img
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
collections:
  - label: 'Blog'
    name: 'blog'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - label: 'Pages'
    name: 'page'
    folder: 'content/pages'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - label: 'Products'
    name: 'product'
    folder: 'content/products'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - label: 'Categories'
    name: 'category'
    folder: 'categories'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - name: "settings"
    label: "Settings"
    extension: "json"
    editor:
      preview: false
    files:
      - file: "src/data/navigation.json"
        label: "Navigation"
        name: "navigation"
        fields: 
          - name: menu
            label: Menus
            widget: list
            fields:
            - name: links
              label: Links
              widget: list
              fields: 
                - {name: title}
                - {name: url}